reverbdotcom/reverb-magento

- app/code/community/Reverb/ProcessQueue/Model/Task/Result/Interface.php
Testing the pull request process
> Remove erroneous comment line

- app/code/community/Reverb/Reports/etc/adminhtml.xml
> Removing Reverb Reports and Bulk Sync page from admin Reports dropdown

- app/code/community/Reverb/ProcessQueue/Helper/Task/Processor.php
- app/code/community/Reverb/Reports/controllers/Adminhtml/Reports/ReverbreportController.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Listings/Index.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Listings/Index/Syncing.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Index.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Creation.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Creation/Task/Processor.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Retrieval.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Sync.php
- app/code/community/Reverb/ReverbSync/Model/Cron/Listings/Sync.php
- app/code/community/Reverb/ReverbSync/Model/Cron/Orders/Creation.php
- app/code/community/Reverb/ReverbSync/Model/Cron/Orders/Retrieval.php
- app/code/community/Reverb/ReverbSync/Model/Cron/Orders/Sync.php
- app/code/community/Reverb/ReverbSync/Model/Exception/Deactivated/Order/Sync.php
- app/code/community/Reverb/ReverbSync/Model/Log.php
- app/code/community/Reverb/ReverbSync/Model/Sync/Order.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/BaseController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Listings/SyncController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Orders/SyncController.php
- app/code/community/Reverb/ReverbSync/etc/adminhtml.xml
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/etc/system.xml
> Trigger for order sync and setting to disable it

- app/code/community/Reverb/Reports/etc/adminhtml.xml
- app/code/community/Reverb/Reports/etc/config.xml
- app/code/community/Reverb/ReverbSync/Helper/Orders/Retrieval.php
- app/code/community/Reverb/ReverbSync/etc/adminhtml.xml
Probably won't fix the underlying issue of #28  but might help and should be done eventually anyway
> Committing more explicit routes for ReverbSync admin routes

- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Listings/Index.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Index.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Retrieval.php
> Fixing issue breaking the order sync admin page

- app/code/community/Reverb/Reports/Block/Adminhtml/Reverbreport/Grid.php
- app/code/community/Reverb/Reports/controllers/Adminhtml/Reports/ReverbreportController.php
- app/design/adminhtml/default/default/layout/reverb_reports.xml
Fix #34 Fixing issue with ajax grid functionality in Reverb Listings Sync Report
> Fix #34 Fixing issue with ajax grid functionality in Reverb Listings Sync Report

- app/code/community/Reverb/ReverbSync/Helper/Data.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Retrieval.php
- app/code/community/Reverb/ReverbSync/Model/Adapter/Curl.php
This patch will help us debug Drum Center's issue
> Logging curl errors when status=0 on a CURL request

- app/code/community/Reverb/Base/Helper/Data.php
- app/code/community/Reverb/ReverbSync/Helper/Data.php
- app/code/community/Reverb/ReverbSync/Model/Adapter/Curl.php
- app/etc/modules/Reverb_ReverbSync.xml
> Setting User-Agent for Reverb API cURL requests

- app/code/community/Reverb/Base/Controller/Adminhtml/Abstract.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Index.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Edit.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Edit/Form.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Index.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Index/Grid.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Unique/Edit.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Unique/Edit/Form.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Unique/Index.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Unique/Index/Grid.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Unique/Index.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Sync.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Orders/Sync/UniqueController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Orders/SyncController.php
- app/code/community/Reverb/ReverbSync/etc/adminhtml.xml
- app/code/community/Reverb/ReverbSync/etc/system.xml
Creates a separate page for the order update tasks grid
> Adding separate admin page for the order update grid

- app/code/community/Reverb/ReverbSync/Model/Sync/Order.php
> Removing serialized object from order creation error

- app/code/community/Reverb/ProcessQueue/Model/Source/Task/Status.php
- app/code/community/Reverb/ProcessQueue/Model/Task.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Index/Grid.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Task/Unique/Index/Grid.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Widget/Grid/Column/Renderer/Order/Product/Abstract.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Widget/Grid/Column/Renderer/Order/Product/Name.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Widget/Grid/Column/Renderer/Order/Product/Sku.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Widget/Grid/Column/Renderer/Order/Reverb/Id.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Widget/Grid/Column/Renderer/Order/Task/Action.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Creation.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Orders/Sync/UniqueController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Orders/SyncController.php
> Setting Reverb Orders to be processed in SuperMode

- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Sales/Order/View/Tab/Reverb.php
- app/design/adminhtml/default/default/template/ReverbSync/sales/order/view/tab/info.phtml
> Fix #77 Fixing Reverb Order view tab to show Reverb ID and Status

- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.4-0.1.5.php
Fix #52
Quickly implemented this one while we were confirming specs for other tasks
> Fix #52 updating crontab schedule to stagger order creations/updates

- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Orders/SyncController.php
Fix #95 
Not critical, but helpful
> Fix #95 Changing queue task success messages to be notices

- app/code/community/Reverb/Reports/controllers/Adminhtml/Reports/ReverbreportController.php
- app/code/community/Reverb/Reports/etc/adminhtml.xml
- app/code/community/Reverb/ReverbSync/Helper/Orders/Sync.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Orders/Sync/UniqueController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/Orders/SyncController.php
- app/code/community/Reverb/ReverbSync/etc/adminhtml.xml
> Consolidate all tabs under one Reverb tab

- app/code/community/Reverb/ReverbSync/Helper/Orders/Creation.php
- app/code/community/Reverb/ReverbSync/Model/Source/Store.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/etc/system.xml
Tested this on 1.9 and 1.7 and it should be good to go
> Create orders in a specified store (for multi-store users)

- app/code/community/Reverb/ReverbSync/Helper/Orders/Creation.php
- app/code/community/Reverb/ReverbSync/Model/Source/Store.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/etc/system.xml
When I first merged this it caused sql failures during sync. Reopened PR to sit here while debugging the issue.
This reverts commit 78c6080cc4e897cfac95372e3051c50abe57c85a.
> Multi-store select dropdown

- app/code/community/Reverb/ReverbSync/Helper/Orders/Update/Cancel.php
- app/code/community/Reverb/ReverbSync/Model/Exception/Data/Order.php
- app/code/community/Reverb/ReverbSync/Model/Exception/Order/Update/Status/Redundant.php
- app/code/community/Reverb/ReverbSync/Model/Observer/Orders/Update.php
- app/code/community/Reverb/ReverbSync/Model/Sync/Order/Update.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
Fix #130 
Code to implement cancelling orders via the Reverb Order Update retrieval process
> Order cancellation

- app/code/community/Reverb/Payment/Model/Method/Reverb.php
- app/code/community/Reverb/Payment/etc/config.xml
- app/code/community/Reverb/ReverbSync/Helper/Orders/Creation.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Update/Abstract.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Update/Cancel.php
- app/code/community/Reverb/ReverbSync/Helper/Orders/Update/Paid.php
- app/code/community/Reverb/ReverbSync/Model/Exception/Data/Order/Update.php
- app/code/community/Reverb/ReverbSync/Model/Observer/Orders/Update.php
- app/code/community/Reverb/ReverbSync/Model/Sync/Order.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
> Unpaid orders are synced in Pending state, no invoice

- app/code/community/Reverb/ProcessQueue/Model/Mysql4/Task.php
> Updating queue task processor

- app/code/community/Reverb/ReverbSync/Model/Mysql4/Category/Magento/Reverb/Mapping.php
> Renamimg misnamed method to something relevant

- app/code/community/Reverb/ReverbSync/Helper/Orders/Creation/Address.php
Fix #144 
This checked out on 1.9 and 1.7. Should be good to go
> Allowing Local Pickup orders to be created in Magento

- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
- app/code/community/Reverb/ReverbSync/Model/Source/Listing/Condition.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.9-0.1.10.php
Fix #120 
Tested this on both 1.9 and 1.7 and it looks good
> Adding functionality to declare listing condition on a per-listing basis

- app/code/community/Reverb/ReverbSync/Model/Source/Listing/Condition.php
- app/code/community/Reverb/ReverbSync/etc/system.xml
A setting for "Default Item Condition" is now an option of predefined set.
> Fix for issue 194

- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Catalog/Product/Tab.php
- app/code/community/Reverb/ReverbSync/Helper/Sync/Product.php
- app/code/community/Reverb/ReverbSync/Model/Observer.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-install-0.1.0.php
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.0-0.1.1.php
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.12-0.1.13.php
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.9-0.1.10.php
Rebased @zztimur's work on current master
> Attribute rename

- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
Note, kept this line just in case:
`if (empty($_attribute_value)) $_attribute_value = $product->getData($_attribute_code);`
Fix #190
> Added support for make/model to be select attributes.

- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
- app/code/community/Reverb/ReverbSync/Model/Source/Listing/Offer.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/etc/system.xml
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.13-0.1.14.php
Added "Accept Offer Attribute".
> Per-product attribute for accepting offers on reverb

- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/etc/system.xml
Mapping for description field. Set to 'description' product attribute by default.
@skwp Should the description update? or should it have a setting for update:yes/no, same as price,title?
> Description can be mapped to a custom field

- app/code/community/Reverb/ReverbSync/Helper/Sync/Listings/Update.php
- app/code/community/Reverb/ReverbSync/Helper/Sync/Product.php
- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
- app/code/community/Reverb/ReverbSync/Model/Observer.php
- app/code/community/Reverb/ReverbSync/Model/Sync/Product.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
Fix #201 Tested on CE 1.9 and 1.7
> magento mass attribute update does not trigger Reverb updates

- app/code/community/Reverb/ReverbSync/Helper/Orders/Retrieval.php
Fix #188 This looks good on my local. 100 order creations were pulled in a single cron iteration; 220 order updates were pulled in a cron iteration as well
> Follow order pagination if there are many orders

- app/code/community/Reverb/ReverbSync/Helper/Data.php
- app/code/community/Reverb/ReverbSync/Helper/Sync/Product.php
- app/code/community/Reverb/ReverbSync/Helper/Task/Processor.php
- app/code/community/Reverb/ReverbSync/Model/Observer.php
- app/code/community/Reverb/ReverbSync/Model/Sync/Product.php
Fix #207 Tested this on 1.7 and 1.9 and it looks good to go.  Tasks are executing via crontab execution as desired
> When saving magento product, reverb sync should be backgrounded [Fix #207]

- app/code/community/Reverb/Base/Controller/Adminhtml/Abstract.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/BaseController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/ReverbSync/Listings/SyncController.php
- app/code/community/Reverb/ReverbSync/etc/adminhtml.xml
> #210 Updating ACL permissions for Reverb Admin category page

- app/code/community/Reverb/ProcessQueue/Block/Adminhtml/Task/Index.php
- app/code/community/Reverb/ProcessQueue/controllers/Adminhtml/ProcessQueue/IndexController.php
- app/code/community/Reverb/ProcessQueue/controllers/Adminhtml/ProcessQueue/Unique/IndexController.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Index.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Orders/Unique/Index.php
- app/code/community/Reverb/ReverbSync/Helper/Admin.php
- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/ReverbSync/Category/SyncController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/ReverbSync/Listings/Image/SyncController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/ReverbSync/Listings/SyncController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/ReverbSync/Orders/Sync/UniqueController.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/ReverbSync/Orders/SyncController.php
- app/code/community/Reverb/ReverbSync/etc/adminhtml.xml
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/etc/system.xml
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.12-0.1.13.php
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.13-0.1.14.php
> Clear actions on certain Reverb admin sections take you on 404 trip [Fix #215]

- app/code/community/Reverb/ReverbSync/Helper/Sync/Listings/Update.php
- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/etc/system.xml
Does not provide support for mass-sync description updates
> Sync description on update

- CHANGELOG.md
- README.md
- app/code/community/Reverb/ReverbSync/Helper/Orders/Retrieval/Update.php
- app/code/community/Reverb/ReverbSync/Model/Adapter/Curl.php
- app/code/community/Reverb/ReverbSync/etc/system.xml
@dunagan5887 any concerns with this?
> Reach back 24 hours for order updates

- app/code/community/Reverb/Base/Controller/Adminhtml/Form/Abstract.php
- app/code/community/Reverb/Base/Controller/Adminhtml/Form/Interface.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Field/Mapping/Edit.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Field/Mapping/Edit/Form.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Field/Mapping/Index.php
- app/code/community/Reverb/ReverbSync/Block/Adminhtml/Field/Mapping/Index/Grid.php
- app/code/community/Reverb/ReverbSync/Model/Field/Mapping.php
- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
- app/code/community/Reverb/ReverbSync/Model/Mysql4/Field/Mapping.php
- app/code/community/Reverb/ReverbSync/Model/Mysql4/Field/Mapping/Collection.php
- app/code/community/Reverb/ReverbSync/Model/Source/Product/Attribute.php
- app/code/community/Reverb/ReverbSync/controllers/Adminhtml/ReverbSync/Field/MappingController.php
- app/code/community/Reverb/ReverbSync/etc/adminhtml.xml
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.15-0.1.16.php
Fix #230 I've tested this and it looks good to me
> Arbitrary field mapping

- app/code/community/Reverb/ReverbSync/Model/Mapper/Product.php
Reverts reverbdotcom/reverb-magento#239
> Revert "Urlencode sku of product listing."

- app/code/community/Reverb/ReverbSync/Helper/Orders/Creation/Address.php
> Handle offers with pending address

- app/code/community/Reverb/ReverbSync/Model/Mysql4/Core/Config.php
- app/code/community/Reverb/ReverbSync/etc/config.xml
- app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.16-0.1.17.php
Fix #254 Tested this on 1.7 and 1.9, should be good to go
> #254 Migration to update all values of "Like New" to "B-Stock"

- composer.json
As a result of creating this file, you will be able to [install this package](https://github.com/Cotya/magento-composer-installer) by adding the URL of this repository and a dependency in your own Magento project.
> Create composer.json to allow installation with Composer
